"""
Django settings for mysite project.

Generated by 'django-admin startproject' using Django 2.0.

For more information on this file, see
https://docs.djangoproject.com/en/2.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.0/ref/settings/
"""

import os
import sys
from .base import *


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ['SECRET_KEY']

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ['*']



# Database
# https://docs.djangoproject.com/en/2.0/ref/settings/#databases

'''
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}
'''
DATABASE_PASSWORD = os.environ['DATABASE_PASSWORD']
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'mysite_db',
        'USER': 'lz',
        'PASSWORD': DATABASE_PASSWORD,
        'HOST': 'localhost',
        'PORT': '3306',
    }
}


# 发送邮件设置
# https://docs.djangoproject.com/en/2.0/ref/settings/#email
# https://docs.djangoproject.com/en/2.0/topics/email/
EMAIL_HOST_PASSWORD = os.environ['EMAIL_HOST_PASSWORD']
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.qq.com'
EMAIL_PORT = 465
EMAIL_HOST_USER = '1094363895@qq.com'
EMAIL_HOST_PASSWORD = EMAIL_HOST_PASSWORD  # 授权码
EMAIL_SUBJECT_PREFIX = '[李朝的博客]'
EMAIL_USE_SSL = True  # 与smtp服务器通信时，是否启动TLS链接（安全链接）

ADMINS = (
	('lz': '1094363895@qq.com'),
)

# 日志文件
# https://docs.djangoproject.com/en/2.1/topics/logging/
LOGGING = {
	'version': 1, # 版本
	'disable_existing_loggers': False, #是否阻止已存在的日志处理器
	'handlers': {
		'file': {
			'level': 'DEBUG',  # 级别
			'class': 'logging.FileHandler',
			'filename': '/home/mysite_debug.log'  # 日志文件所在位置
		},
		'mail_admins': {  # 发生错误给管理员发邮件
			'level': 'ERROR',
			'class': 'django.utils.log.AdminEmailHandler',
		}
	},
	'loggers': {  # 日志处理器
		'django': {
			'handlers': ['file'],  # 规定启用file处理程序，这个file就是上面的file
			'level': 'DEBUG',
			'propagate': True,   # 是否向上传递错误
		},
		'django.request': {  # 日志记录器就是记录用哪些处理器
			'handlers': ['mail_admins'],
			'level': 'ERROR',
			'propagate': False,
		},
	},
}